### PR TITLE
Added a Navbar

### LINKED ISSUE #13: Redesign the Navbar.
We can redesign the navbar like adding proper privacy page link and terms and condition. Like giving it proper section.

### PR DESCRIPTION
**Pull request by HeatBlastee**
## Fixes Issue
Added a navbar

## Changes proposed
- Added a navbar with improved styling.
- Increased the size and font of the navbar.
- Enhanced hover effects for better user experience.

## Check List
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

## Note to reviewers
Please check the navbar on different links.

### CODE REVIEW

**Comment by pooranjoyb** [comment]
As you mentioned that you'll be adding links to terms and conditions, but i can see that you've added the NavLinks to the pages which exists in mobile version and not in desktop view. Please  clarify. @HeatBlastee

**Review by pooranjoyb — CHANGES_REQUESTED** [review]
As you mentioned that you'll be adding links to terms and conditions, but i can see that you've added the NavLinks to the pages which exists in mobile version and not in desktop view. Please  clarify. @HeatBlastee

**Comment by HeatBlastee** [comment]
Actually I am not able to understand. Like in files you have added navbar at last so do you want something like footer which has all the links and regarding adding links there's no Terms and Condition page so do you want me to make one and add links in both desktop and mobile view

**Comment by pooranjoyb** [comment]
Ok then will assign to another issues when there.

**Pull request closed without merging**
