### PR TITLE
Fixes #68: Improved UI Styling

### LINKED ISSUE #68: [BUG] No Hover Effect on "Support Us" and "GitHub" Button
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The "Support Us" and "GitHub" buttons lack a hover effect. When the cursor is moved over these buttons, there is no visual feedback (like a color change, underline, or shadow) to indicate interactivity, which might confuse users or make the UI less intuitive.

### Screenshots

Video

https://github.com/user-attachments/assets/bbab72a4-a8c2-44cb-a32d-0845aed9db82

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Steps to Reproduce:

1. Open the webpage where the "Support Us" and "GitHub" buttons are located.
2. Move the cursor over the "Support Us" and "GitHub" buttons.
3. Observe the absence of any hover effect or visual response.

### PR DESCRIPTION
**Pull request by ad1tyayadav**
## Fixes Issue
Closes #68

## Check List
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Video

https://github.com/user-attachments/assets/8f57c6e4-f923-4189-aacc-be5730e7f266

### CODE REVIEW

**Comment by sristy17** [comment]
> ## Fixes Issue
> Closes #68
> 
> ## Check List
> * [x]  My code follows the code style of this project.
> * [x]  My change requires changes to the documentation.
> * [x]  I have updated the documentation accordingly.
> * [x]  All new and existing tests passed.
> * [x]  This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## Video
>  Screen.Recording.2024-12-17.111510.mp4

@ad1tyayadav seems good but donot raise a pr without getting assign the issue, also will merge the pr if u do some more changes, u can try with the error page try to match the theme of the error page.

**Comment by ad1tyayadav** [comment]
@sristy17 Error page theme done please check this pr [569abcd](https://github.com/sristy17/MindDrive/pull/70/commits/569abcd03c77247a1dbcc10e52a893c3f7de4d99) and for button styling check this [c2941a1](https://github.com/sristy17/MindDrive/pull/70/commits/c2941a196cf3bdba031f7693749ba419efa533bd) . 
Sorry for raising pr without asking.

**Comment by sristy17** [comment]
> @sristy17 Error page theme done please check this pr [569abcd](https://github.com/sristy17/MindDrive/pull/70/commits/569abcd03c77247a1dbcc10e52a893c3f7de4d99) and for button styling check this [c2941a1](https://github.com/sristy17/MindDrive/pull/70/commits/c2941a196cf3bdba031f7693749ba419efa533bd) . Sorry for raising pr without asking.

create a single pr for both. Ig the new one has both the changes?

**Comment by ad1tyayadav** [comment]
> Owner

Yes you are right.

**Comment by sristy17** [comment]
> > Owner
> 
> Yes you are right.

i am closing this pr. will merge the new one.

**Pull request closed without merging**
