### PR TITLE
User Authentication

### LINKED ISSUE #3: User Authentication (Signup)
- Use the `collection.json` from Release and import it to your Postman.
- Use the predefined routes to test the APIs
- Integrate the Signup feature

### LINKED ISSUE #33: [FEATURE] Auth Management
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Tasks : 

- As of now, after the logins, or signups, nothing happens, just the success/failure response.

### Proposed Solution

- So, on successful Login, save the Auth Data to localstorage with the key "authData" and navigate the user to Home Page 
- Create a Logout button in the top-right corner of the Navbar in PWA to Logout the user
- Clear the local storage on Logout.

### Screenshots

Use this Logout button,

https://icons.getbootstrap.com/icons/box-arrow-left/

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by theCodeCrusaderX**
login form

user signin done

### CODE REVIEW

**Comment by theCodeCrusaderX** [comment]
one more thing that i wana ask form u because i am new to open source .

waiting

why i am seeing my progress still 0/4 [1 waiting ]

as u said u merged the pull request 

will i get seperate pull request for signin too...???

**Review by pooranjoyb — APPROVED** [review]

**Comment by pooranjoyb** [comment]
Ready to merge @sristy17 🚀

**Comment by pooranjoyb** [comment]
> one more thing that i wana ask form u because i am new to open source .
> 
> waiting
> 
> why i am seeing my progress still 0/4 [1 waiting ]
> 
> as u said u merged the pull request
> 
> will i get seperate pull request for signin too...???

will take 1 week to verify from hacktoberfest admins.

**Comment by theCodeCrusaderX** [comment]
okay thankx and i am glad that i started my first contribution from your repo

**Pull request merged**
