### PR TITLE
Fix/issue 68 & match error page theme

### LINKED ISSUE #68: [BUG] No Hover Effect on "Support Us" and "GitHub" Button
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The "Support Us" and "GitHub" buttons lack a hover effect. When the cursor is moved over these buttons, there is no visual feedback (like a color change, underline, or shadow) to indicate interactivity, which might confuse users or make the UI less intuitive.

### Screenshots

Video

https://github.com/user-attachments/assets/bbab72a4-a8c2-44cb-a32d-0845aed9db82

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Steps to Reproduce:

1. Open the webpage where the "Support Us" and "GitHub" buttons are located.
2. Move the cursor over the "Support Us" and "GitHub" buttons.
3. Observe the absence of any hover effect or visual response.

### PR DESCRIPTION
**Pull request by ad1tyayadav**
## Fixes Issue
Closes #68 

## Changes proposed
- [x] Match the theme of error page
- [X] Improve button styling

## Check List 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x]This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

### CODE REVIEW

**Comment by sristy17** [comment]
> ## Fixes Issue
> Closes #68
> 
> ## Changes proposed
> * [x]  Match the theme of error page
> * [x]  Improve button styling
> 
> ## Check List
> * [x]  My code follows the code style of this project.
> * [x]  My change requires changes to the documentation.
> * [x]  I have updated the documentation accordingly.
> * [x]  All new and existing tests passed.
> * [x]This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots
> image

make the theme darker, maybe by changing the image or anything.

**Comment by sristy17** [comment]
@ad1tyayadav make all the changes in this pr.

**Comment by ad1tyayadav** [comment]
> @ad1tyayadav make all the changes in this pr.
okay

**Comment by ad1tyayadav** [comment]
@sristy17 Hi! I have completed all the requested changes. Please take a look.

Screenshot 2024-12-17 200042

**Review by pooranjoyb — APPROVED** [review]

**Pull request merged**
